id: tour_generator
type:
  - onload
  - tool-menu
# this is now upstream since 25.1 and we don't need this webhook
activate: false

icon: fa-puzzle-piece
title: Generate Tour

function: >
  if (typeof TourGenerator !== 'undefined') {
    new TourGenerator({
      toolId: options.id,
      toolVersion: options.version
    });
  } else {
      console.error("Tour generator is not loaded.  Please report this to a Galaxy administrator.")
  }
